### ISSUE TITLE
wrong ncnn model

### ISSUE THREAD

**Issue by slz929** [MichiganLu/Superpoint_android#4]
I find your project with bad results.
because your ONNX model is not same with exported NCNN model.
ONNX : 3 permute op:
![image](https://github.com/MichiganLu/Superpoint_Android/assets/17669514/536e8c3c-fd9e-419d-9cbe-b406d8528969)

NCNN model: 2 permute op:
![image](https://github.com/MichiganLu/Superpoint_Android/assets/17669514/51fc9cf4-fff5-4f74-b2fb-32bce74ed5ea)

**Comment by MichiganLu** [comment]
I am not maintaining this repo anymore. But just so you know, the model was tested with a product team, which meant it should work.
